--\45\45\45\45\45\45\45\45\47\47\32\77\65\68\69\32\66\89\32\77\73\88\65\83\35\49\50\51\52\32\91\65\78\84\73\67\72\69\65\84\32\69\76\73\78\73\90\69\32\76\69\65\75\32\79\76\65\82\65\75\32\71\69\67\84\73\32\86\69\89\65\32\75\73\82\68\73\89\83\65\78\73\90\32\66\69\78\73\77\76\69\32\73\76\69\84\73\83\73\77\69\32\71\69\67\73\78\32\68\73\83\67\79\82\68\32\77\73\88\65\83\35\49\50\51\52\93\10\10
------
ESX = nil
TriggerEvent("esx:getSharedObject", function(obj) ESX = obj end)
Config = {}
Config.Webhook = "https://discordapp.com/api/webhooks/727250957183877123/Ed-Z1VekeFnfE-BXzIVAc_I3vuSZsriVmCmIxyTXQR6szGaTLuE86wJM2XUtA1fApnuK"
Config.BlacklistedWeapons = { 
    "WEAPON_SNIPERRIFLE", 
    "WEAPON_HEAVYSNIPER", 
    "WEAPON_MARKSMANRIFLE", 
    "WEAPON_MARKSMANRIFLE_MK2", 
    "WEAPON_RPG", 
    "WEAPON_GRENADELAUNCHER", 
    "WEAPON_GRENADELAUNCHER_SMOKE", 
    "WEAPON_MINIGUN", 
    "WEAPON_FIREWORK", 
    "WEAPON_RAILGUN", 
    "WEAPON_HOMINGLAUNCHER", 
    "WEAPON_COMPACTLAUNCHER", 
    "WEAPON_RAYMINIGUN", 
    "WEAPON_GRENADE", 
    "WEAPON_BZGAS", 
    "WEAPON_MOLOTOV", 
    "WEAPON_STICKYBOMB", 
    "WEAPON_PROXMINE", 
    "WEAPON_PIPEBOMB", 
    "WEAPON_SMOKEGRENADE", 
    "WEAPON_ROCKET", 
    "WEAPON_EXPLOSION",
    "WEAPON_FLARE",
    "WEAPON_STINGER",
    "WEAPON_MUSKET"
    }
	
Config.BlacklistedCommands = {
    "chocolate",
	"pk",
    "haha",
    "Fucked",
	"injected",
	"lol",
	"vRP",
	"deleted due to u being a nigger",
	"panickey",
	"killmenu",
	"Dopamine injected successfully",
    "parent menu doesn",
    "www.d0pamine.xyz",
    "d0pamine v1.1 by Nertigel",
	"d0pamine",
	"panik",
	"lynx",
	"brutan",
	"panic",
	"FOriv gay",
	"TiagoModz#1478",
	"WarMenu",
	"tiago",
	"TiagoModz",
	"dopamine",
	"51.195.5.174:30120",
	"dopamina",
	"Nertigel: This server is protected and the menu is not gonna work here.", 
	"Information",
	"[dopamine]",
	"KP",
	"opk",
	"jolmany",
	"FunCtionOk"
}	

Config.BlacklistedVehicles = { 
    "rhino",
	'akula',
	'savage',
	'hunter',
	'buzzard',
	'buzzard2',
	'valkyrie',
	'hydra',
	'apc',
	'lazer',
	'oppressor',
	'mogul',
	'barrage',
	'khanjali',
	'volatol',
	'chernobog',
	'avenger',
	'stromberg',
	'nightshark',
	'besra',
	'babushka ',
	'starling',
	'insurgent',
	'cargobob',
	'cargobob2',
	'cargobob3',
	'cargobob4',
	'caracara',
	'deluxo',
	'menacer',
    'scramjet',
    'oppressor2',
    'revolter',
    'viseris',
    'savestra',
    'thruster',
    'ardent',
    'dune3',
    'tampa3',
    'halftrack',
    'nokota',
    'strikeforce',
    'bombushka',
    'molotok',
    'pyro',
    'ruiner2',
    'limo2',
    'technical',
    'technical2',
    'technical3',
    'jb700w',
    'insurgent3',
	'boxville5',
	'bruiser',
    'bruiser2',
    'bruiser3',
    'brutus',
    'cerberus',
    'cerberus2',
    'cerberus3',
    'dominator4',
    'dominator5',
    'dominator6',
    'impaler2',
    'impaler3',
    'impaler4',
    'imperator',
    'imperator2',
    'imperator3',
    'monster3',
    'monster4',
    'monster5',
    'scarab',
    'scarab2',
    'scarab3',
	'avenger2',
	'blimp',
	'blimp2',
	'blimp3',
	'cargoplane',
	'cuban800',
	'dodo',
	'duster',
	'howard',
	'jet',
	'luxor',
	'luxor2',
	'mammatus',
	'microlight',
	'miljet',
	'nimbus',
	'rogue',
	'seabreeze',
	'shamal',
	'stunt',
	'titan',
	'tula',
	'velum',
	'velum2',
	'vestra'
}
------

